services:
    knu-room-mate-db:
        image: postgres:15
        restart: always
        volumes:
            - ./docker:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: knu-room-mate
            POSTGRES_PASSWORD: knu-room-mate
            POSTGRES_DB: knu-room-mate
